[package]
name = "eater_domainmatcher"
description = "light weight and fast (probably) domain pattern matcher"
version = "0.1.1"
license = "MIT"
edition = "2021"

[dependencies]
smallvec = { optional = true, version = "1" }

[features]
smallvec = ["dep:smallvec"]
